---
    - name: Nginx installation
      hosts: all
      become: yes
      tasks:  
        - name: Update apt-get repo and cache
          ansible.builtin.apt: 

        - name: Install nginx
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
          loop: 
            - ca-certificates
            - curl
            - gnupg
        - name: Add an Apt signing key, uses whichever key is at the URL
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg 
            state: present
        - name: add docker repository to apt
          ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu bionic stable
            state: present
        - name: Update APT cache
          ansible.builtin.apt:
            update_cache: yes
        - name: Install Docker and related packages
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
          loop:
            - docker-ce
            - docker-ce-cli
            - containerd.io
        